constituency_area_mapping = {
    "Accra Metropolitan / ABLEKUMA CENTRAL": [
        "Abossey Okai",
        "Mataheko",
        "Adwenbu",
        "Gbortsui",
        "Mambrouk",
        "Lartebiokorshie",
        "Nmenmeete",
    ],
    "Accra Metropolitan / ABLEKUMA NORTH": [
        "West Darkuman",
        "East Darkuman",
        "Kwashieman",
        "Awoshie",
        "Odorkor",
        "Otaten",
        "Sakaman",
    ],
    "Accra Metropolitan / ABLEKUMA SOUTH": [
        "Korle Gonno",
        "Korle Bu",
        "Mamprobi",
        "Chorkor",
    ],
    "Accra Metropolitan / ABLEKUMA WEST": [
        "New Mamprobi",
        "Gbebu",
        "Shiabu",
    ],
    "Accra Metropolitan / AYAWASO EAST": [
        "Nima East",
        "Nima West",
    ],
    "Accra Metropolitan / KLOTTEY KORLEY": [
        "Official Town",
        "Odaw-Naa/Sahara",
        "North Adabraka",
        "Tudu",
        "Asylum Down",
        "Kinkawe",
        "Alata",
        "Osu Doku",
        "Ringway Estates",
    ],
    "Accra Metropolitan / ODODODIODIOO": [
        "Ngleshie",
        "Mudor",
        "Kinka",
        "Nmlitsagonno",
        "Korle Wonkon",
        "Amamomo",
        "Korle Dudor",
    ],
    "Accra Metropolitan / OKAIKWEI CENTRAL": [
        "Kantseian",
        "Apenkwa",
        "Wuoyeman",
        "Blema Gor",
        "Olengele Koona",
        "Gbemomo",
    ],
    "Accra Metropolitan / OKAIKWEI SOUTH": [
        "Kaneshie",
        "Awudome",
        "Avenor",
        "Gonten",
        "Mukose",
        "Bubiashie",
    ],
    "Ablekuma West Municipal / ABLEKUMA WEST": [
        "Opetekwei",
        "Mampong Okai",
        "Mansralor",
    ],
    "Ayawaso Central Municipal / AYAWASO CENTRAL": [
        "Kokomlemle East",
        "Kokomlemle West",
        "Aryee Diki",
        "Kotobabi",
        "Alajo",
        "Abelenkpe",
        "Roman Ridge/Airport Res. Area",
    ],
    "Ayawaso North Municipal / AYAWASO NORTH": [
        "Kwaotsuru",
        "Mamobi East",
        "Mamobi West",
    ],
    "Ayawaso West Municipal / AYAWASO WEST WUOGON": [
        "Dzorwulu",
        "Legon",
        "Okponglo",
        "East Legon",
    ],
    "Okaikwei North Municipal / OKAIKWEI NORTH": [
        "Anorhuma",
        "Nii Boiman",
        "Akweteman",
        "Achimota",
        "Abofu",
        "Anumle",
    ],
    "Ada West District / SEGE": [
        "Sege/Koni",
        "Badzoohe/Luta",
        "Nakomkope",
        "Bonikope",
        "Toflokpo",
        "Matsekope",
        "Koluedor",
        "Hwakpo/Addokope",
        "Afiadenyigba",
        "Caesarkope",
        "Wekumagbe",
        "Akplabanya",
        "Anyamam",
        "Goi",
        "Lolonya",
    ],
    "Ada East District / ADA": [
        "Kasseh",
        "Asigbekope",
        "Bedeku",
        "Tamatoku",
        "Dogo/Togbloku",
        "Amlakpo",
        "Atortorkope",
        "Gorm",
        "Tuanikope/Pediatorkope",
        "Kpono Abossey",
        "Kudziragbe",
        "Kabiaweyumu",
        "Alata",
        "Lomobiawe",
        "Luhuese",
        "Foahwem",
        "Teimensapanya",
        "Lolonyakope",
        "Kewunor",
        "Fiagbedu",
        "Aflive/Azizakpe/Alorkpem",
        "Zongo",
        "Ocanseykope",
        "Futuenya/Otrokpe",
        "Anyakpor/Adedetsekope",
        "Alavanyo",
        "Pute",
    ],
    "Adentan Municipal / ADENTAN": [
        "Adjiringanor",
        "Otanor",
        "Nmai Dzorn",
        "Nii Asharley",
        "Ogbojo",
        "Man Hee",
        "Gbentanaa",
        "Man Momo",
        "New Adenta",
        "New Legon",
        "Koose",
        "Amrahia-Marledjor",
    ],
    "Ashaiman Municipal / ASHAIMAN": [
        "Nii Tetteh Amui East",
        "Nii Tetteh Amui West",
        "Tettey Nkpa",
        "Nii Annan Adjor",
        "Tsinai-Agber",
        "Oko Mantey",
        "Naa Amerley",
        "Naa Amui",
        "Manmomo",
        "Tebibii Anno",
        "Obaakatse",
        "Nii Doku",
        "Mantseman",
        "Emaohie",
        "Nii Komieteh",
        "Moni Obaanye",
        "Nii Man",
    ],
    "Ga Central Municipal / ANYAA SOWUTUOM": [
        "Awoshie",
        "Anyaa",
        "Ablekuma",
        "Santa Maria",
        "Sowutuom",
        "Lomnava",
        "Nii Okaiman West",
        "Nii Okaiman East",
        "Kwashie Bu",
    ],
    "Ga South Municipal / NGLESHI AMANFRO": [
        "Ngleshie Amanfro",
        "Galilea",
        "Bortianor",
        "Gedan Tuba",
        "Kokrobitey",
        "Akwasa",
    ],
    "Ga South Municipal / NGLESHI WEIJA GBAWE": [
        "Weija",
        "New Weija",
        "Oblogo",
        "Mallam",
        "Gbawe",
        "New Gbawe",
        "Macarthy Hill",
    ],
    "Ga South Municipal / DOMEABRA OBOM": [
        "Nsuobri",
        "Akweiman",
        "Jei-Krodua",
        "Honi-Afajator",
        "Panfo",
        "Obom",
        "Oduman-Asuaba",
        "Paanor",
        "Kofi Kwei",
        "Gbemomo",
        "Danchira",
        "Ashalaja",
        "Hobor",
    ],
    "Ga East Municipal / DOME KWABENYA": [
        "Abokobi",
        "Abladjei",
        "Agbogba",
        "Haatso",
        "Atomic",
        "Kwabenya",
        "Dome East",
        "Dome West",
        "Taifa South",
        "Taifa North",
    ],
    "Ga West Municipal / TROBU": [
        "Trobu",
        "Tantra",
        "Nii Ankraman",
        "Ofankor",
        "Asofa",
        "Pokuase",
        "Fise",
        "Afiaman",
    ],
    "Ga West Municipal / AMASAMAN": [
        "Dedeiman",
        "Mayera",
        "Gonno",
        "Samsam",
        "Amasaman",
        "Sarpeiman",
        "Kutunse",
        "Medie",
        "Akotoshie",
        "Kotoku",
        "Achiaman",
        "Kwashiekuma",
        "Onyansana",
        "Okushiebiade",
        "Ayikai-Doblo",
        "Nsakina",
        "Manhean",
    ],
    "La Dade Kotopon Municipal / DADE KOTOPON": [
        "Ako - Adjei",
        "New Kaajarno (Kaa-Jarno)",
        "Abafum / Abese/Kowe",
        "New Lakpanaa (Lakpanaa)",
        "Adiembra",
        "Mantiase / Tse - Ado (Mantiase)",
        "Adobetor",
        "Labone",
        "Cantonments",
        "Burma Camp",
    ],
    "La Nkwantanang Madina Municipal / MADINA": [
        "Danfa",
        "Oyarifa",
        "Pantang",
        "West Adentan",
        "Madina West",
        "North Legon",
        "Tatanaa",
        "Social Welfare",
        "Nkwantanang",
    ],
    "Ledzekuku Municipal / LEDZOKUKU": [
        "West Akromadeokpo",
        "East Akromadeokpo",
        "Agbelejor",
        "Lekma Hospital",
        "Ajahman",
        "Nanakrom",
        "Kojo Abese",
        "Nii Dowuona North",
        "Nii Dowuona South",
        "Lekma Central",
        "Nii Ashitey Akomfra",
        "Agbawe",
        "Dangme",
    ],
    "Tema Metropolitan / TEMA WEST": [
        "New Lashibi",
        "Community 2",
        "Community 5",
        "Community 8",
        "Community 20",
        "Community 22",
    ],
    "Tema Metropolitan / TEMA CENTRAL": [
        "Harbour/Community 2",
        "Tema Central North",
        "Tema Central East",
        "Tema Central West",
        "Harbour North",
    ],
    "Tema Metropolitan / TEMA EAST": [
        "Tema East North",
        "Tema East South",
        "Tema East Central",
        "Newtown",
        "Manhean",
        "Awudum",
    ],
    "Shai Osudoku District / OSUDOKU": [
        "Volivo",
        "Ayikuma",
        "Doryumu",
        "Asutsuare",
        "Adumanya",
        "Agomeda",
        "Osuwem",
        "Dufour",
        "Kutunse",
        "Korwe",
    ],
    "Ningo Prampram District / NINGO PRAMPRAM": [
        "Prampram",
        "Kley",
        "Dawa",
        "Mangotsonya",
        "Old Ningo",
        "Agbami",
    ],
    "Tema West Municipal / TEMA WEST": [
        "Tsuibleoo",
        "Community 12",
        "Community 11",
        "Community 10",
    ]
}

