# Generated by Django 5.0.6 on 2024-06-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_unitofmeasurement_product_product_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
