# Generated by Django 5.0.6 on 2024-07-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_total_cost_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
