# Generated by Django 5.0.6 on 2024-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='core.product'),
        ),
    ]
