# Generated by Django 5.0.6 on 2024-07-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
