# Generated by Django 5.0.6 on 2024-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_productvariant_min_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='min_order_value',
        ),
        migrations.AddField(
            model_name='category',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
