# Generated by Django 5.0.6 on 2024-08-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasurement'),
        ),
    ]
