# Generated by Django 5.0.6 on 2024-08-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_orderitem_unit_of_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.productvariant')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='core.unitofmeasurement')),
            ],
            options={
                'unique_together': {('product_variant', 'unit_of_measurement')},
            },
        ),
    ]
