# Generated by Django 5.0.6 on 2024-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_productvariantprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='unit',
            field=models.CharField(choices=[('BAGS', 'Bags'), ('PIECES', 'Pieces'), ('TRIPS', 'Trips'), ('TONNES', 'Tonnes'), ('CUBIC_METERS', 'Cubic Meters')], default='PIECES', max_length=20),
        ),
    ]
