# Generated by Django 5.0.6 on 2024-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_deliveryfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfee',
            name='weight_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
