# Generated by Django 5.0.6 on 2024-12-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_deliveryfee_weight_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
